runtime: nodejs18

#instance_class: F4_1G
instance_class: F2

env_variables:
  NEXT_PUBLIC_API_URL: "https://portfolio-backend-dot-genial-cab-394408.du.r.appspot.com"
  NEXT_PUBLIC_ENV: 'production'

